// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4GDCW8MA0o3LyLbNu2KTU7LxXyTfk460',
    appId: '1:892946571197:web:624abe442cfbd6ea1ebcd4',
    messagingSenderId: '892946571197',
    projectId: 'gamifier-hackathon',
    authDomain: 'gamifier-hackathon.firebaseapp.com',
    storageBucket: 'gamifier-hackathon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo9Dp8vevpmDSVPCYo-jUB_XbDWYW2JnU',
    appId: '1:892946571197:android:f9fb116e8652ab641ebcd4',
    messagingSenderId: '892946571197',
    projectId: 'gamifier-hackathon',
    storageBucket: 'gamifier-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv7qzkXB19CqZ-pFb37xoRIIgqK5LBRP4',
    appId: '1:892946571197:ios:e4950e82ac8f6f641ebcd4',
    messagingSenderId: '892946571197',
    projectId: 'gamifier-hackathon',
    storageBucket: 'gamifier-hackathon.appspot.com',
    iosBundleId: 'com.example.societeGeneraleGamification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4GDCW8MA0o3LyLbNu2KTU7LxXyTfk460',
    appId: '1:892946571197:web:67df6b6a7593f3591ebcd4',
    messagingSenderId: '892946571197',
    projectId: 'gamifier-hackathon',
    authDomain: 'gamifier-hackathon.firebaseapp.com',
    storageBucket: 'gamifier-hackathon.appspot.com',
  );
}
